# Generated by Django 4.2.1 on 2024-12-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_platform', '0002_remove_video_id_video_uploaded_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('video_file', models.FileField(upload_to='videos/')),
            ],
        ),
    ]
