# Generated by Django 4.2.1 on 2024-12-04 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_platform', '0003_videohome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoHome',
        ),
    ]
